language: python
dist: focal
cache: pip3

python:
  - "3.8"

branches:
  only:
    - master

install:
  - ./install_dependencies
  - pip install -r requirements-test.txt

script:
  - ./run-qa-checks
  - python3 downloader.py
  - ls
  # - python3 main.py
  # - python3 test.py

after_success:
  coveralls
