language: python
dist: focal
cache: pip3

python:
  - "3.8"

addons:
  apt:
    packages:
      - libportaudio2
      - libsndfile1-dev
      - ffmpeg

branches:
  only:
    - master

install:
  - pip install -r requirements.txt

script:
  - python3 downloader.py
  - ls

after_success:
  coveralls