language: python
dist: focal
cache: pip3

python:
  - "3.8"

addons:
  apt:
    packages:
      - libportaudio2
      - libsndfile1-dev
      - ffmpeg

branches:
  only:
    - live-audio
    - master

install:
  - pip install -r requirements.txt

script:
  - python3 downloader.py
  - ls
  - python3 dvec_gen.py
  # - python3 main.py
  # - python3 test.py

after_success:
  coveralls