#!/bin/bash
set -e

# Linux packages
sudo apt update
sudo apt-get install libportaudio2
sudo apt-get install libsndfile1-dev
sudo apt-get install ffmpeg

# Python libraries
pip install -r requirements.txt

echo -e '\033[33;1mAll dependencies are installed :)\033[0m'
